# Site settings
title: angular_init (ngi)
email: frontendcollisionblog@gmail.com
url: http://joshbeam.github.io
baseurl: /angular_init
#baseurl: 
description: "angular_init is the simple AngularJS template generator"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/joshbeam92
  - title: stack-overflow
    url: http://careers.stackoverflow.com/joshbeam
  - title: github
    url: https://github.com/joshbeam/angular_init

# Build settings
markdown: kramdown
permalink: pretty

sass:
    sass_dir: _sass